name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.0-6
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: Liga-dos-Programadores/liga-dos-programadores.github.io
          publish_dir: .
          keep_files: true
          publish_branch: master
